apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: igetit-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: igetit-app
    spec:
      containers:
      - name: nginx
        image: nginx
        ports:
        - containerPort: 80
      - name: igetit-app
        image: igetit
        # for local development against minikube registry
        #imagePullPolicy: Never

---
apiVersion: v1
kind: Service
metadata:
  name: igetit-service
  labels:
    app: igetit-service
spec:
  type: NodePort
  ports:
    # the port that this service should serve on
    - port: 80
  # label keys and values that must match in order to receive traffic for this service
  selector:
    app: igetit-app
